# ========================
# Clash-ALL ä¼˜åŒ–é…ç½®
# ========================

# æœºåœºèŠ‚ç‚¹è®¢é˜…

proxy-providers:
  Sakuraca:
    url: ""
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    override:
      additional-prefix: "Sakuraca-"
    exclude-filter: "x|å€|æ¶ˆè€—|å®˜ç½‘|åˆ°æœŸ|é‡ç½®|å‰©ä½™|æµ·å¤–"
    proxy: ç›´è¿
  SaySS:
    url: ""
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    override:
      additional-prefix: "SaySS-"
    exclude-filter: "x|å€|æ¶ˆè€—|å®˜ç½‘|åˆ°æœŸ|é‡ç½®|å‰©ä½™|æµ·å¤–"
    proxy: ç›´è¿
  CockCloud:
    url: ""
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    override:
      additional-prefix: "CockCloud-"
    exclude-filter: "x|å€|æ¶ˆè€—|å®˜ç½‘|åˆ°æœŸ|é‡ç½®|å‰©ä½™|æµ·å¤–"
    proxy: ç›´è¿
   

proxies:
  - {name: ç›´è¿, type: direct}
  - {name: æ‹’ç», type: reject}

# å—…æ¢ï¼ˆfakeipä¸‹å…¶å®å¯ä»¥ä¸ç”¨å—…æ¢ï¼‰
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: false
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
    

# å…¨å±€é…ç½® 
mixed-port: 7890
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
tcp-concurrent: true
log-level: warning
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

#external-controller: 0.0.0.0:9090
#external-ui: ui
#external-ui-name: zashboard
#external-ui-url: https://gh-proxy.com/github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip
#secret: "123456"

# ========================
# DNS è®¾ç½®
# ========================
dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:1053
  ipv6: true
  respect-rules: true
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:fakeipfilter_domain,cn_domain"
#    - "geosite:cn"
    - "+.hs.net"
    - "*.lan"
  nameserver-policy:
    "rule-set:cn_domain,private_domain":
      - system
    "rule-set:geolocation-!cn":
      - https://8.8.8.8/dns-query
      - https://1.1.1.1/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  direct-nameserver:
    - system
  nameserver:
    - https://8.8.8.8/dns-query
  fallback:
    - https://8.8.8.8/dns-query
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - ::/128
      - ::1/128
      - 2001::/32
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"



   


# å…¥ç«™
#tun:
#  enable: true
#  #system/gvisor/mixed
#  stack: mixed
#  dns-hijack: ["any:53", "tcp://any:53"]
#  #ä½¿ç”¨nikkiï¼Œæ··å…¥å…¨éƒ¨ä¸ä¿®æ”¹çš„æƒ…å†µï¼Œå¼€å¯æ¥å£æŒ‡å®šä¸ºnikki
#  #device: nikki
#  #ä½¿ç”¨ä»…å†…æ ¸è‡ªè¡Œä¿®æ”¹ä¸‹é¢ä¸‰é¡¹ä¸ºtrue
#  auto-route: false
#  auto-redirect: false
#  auto-detect-interface: false


# ========================
# ç­–ç•¥ç»„å®šä¹‰
# ========================
default: &default
  type: select
  proxies:
    - ğŸš€ é»˜è®¤ä»£ç†
    - â™»ï¸ æ‰€æœ‰-è‡ªåŠ¨
    - ğŸ”¯ é¦™æ¸¯-æ•…è½¬
    - ğŸ”¯ å°æ¹¾-æ•…è½¬
    - ğŸ”¯ æ—¥æœ¬-æ•…è½¬
    - ğŸ”¯ æ–°åŠ å¡-æ•…è½¬
    - ğŸ”¯ éŸ©å›½-æ•…è½¬
    - ğŸ”¯ ç¾å›½-æ•…è½¬
    - ğŸ”¯ è‹±å›½-æ•…è½¬
    - ğŸ”¯ å…¶ä»–-æ•…è½¬
    - ç›´è¿
    - æ‹’ç»
default_no_allmanual: &default_no_allmanual
  type: select
  proxies:
    - â™»ï¸ æ‰€æœ‰-è‡ªåŠ¨
    - ğŸ”¯ é¦™æ¸¯-æ•…è½¬
    - ğŸ”¯ å°æ¹¾-æ•…è½¬
    - ğŸ”¯ æ—¥æœ¬-æ•…è½¬
    - ğŸ”¯ æ–°åŠ å¡-æ•…è½¬
    - ğŸ”¯ éŸ©å›½-æ•…è½¬
    - ğŸ”¯ ç¾å›½-æ•…è½¬
    - ğŸ”¯ è‹±å›½-æ•…è½¬
    - ğŸ”¯ å…¶ä»–-æ•…è½¬
    - ç›´è¿
    - æ‹’ç»

proxy-groups:

  # ä¸šåŠ¡åˆ†æµç»„
  - {name: ğŸš€ é»˜è®¤ä»£ç†, <<: *default_no_allmanual, include-all: true,filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$"}
#  - {name: ğŸš€ é»˜è®¤ä»£ç†, <<: *default}
  - {name: ğŸ“¹ YouTube, <<: *default}
  - {name: ğŸ€ Google, <<: *default}
  - {name: ğŸ¤– ChatGPT, <<: *default}
  - {name: ğŸ‘¨ğŸ¿â€ğŸ’» GitHub, <<: *default}
  - {name: ğŸ¬ OneDrive, <<: *default}
  - {name: ğŸªŸ Microsoft, <<: *default}
  - {name: ğŸµ TikTok, <<: *default}
  - {name: ğŸ“² Telegram, <<: *default}
  - {name: ğŸ¥ NETFLIX, <<: *default}
  - {name: ğŸ’¶ PayPal, <<: *default}
  - {name: ğŸ® GAME-CN, <<: *default}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, <<: *default}

#  - name: ğŸ– æ‰€æœ‰-æ‰‹åŠ¨
#    type: select
#    include-all: true
#    filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$"

  - name: â™»ï¸ æ‰€æœ‰-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$"

  # é¦™æ¸¯ç»„
  - name: ğŸ”¯ é¦™æ¸¯-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-æ‰‹åŠ¨
      - â™»ï¸ é¦™æ¸¯-è‡ªåŠ¨
  
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong)).*$"
    
  - name: â™»ï¸ é¦™æ¸¯-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong)).*$"
 
  # å°æ¹¾ç»„
  - name: ğŸ”¯ å°æ¹¾-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾-æ‰‹åŠ¨
      - â™»ï¸ å°æ¹¾-è‡ªåŠ¨
  - name: ğŸ‡¹ğŸ‡¼ å°æ¹¾-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|TaiWan|Taiwan)).*$"
  - name: â™»ï¸ å°æ¹¾-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|TaiWan|Taiwan)).*$"

  # æ—¥æœ¬ç»„
  - name: ğŸ”¯ æ—¥æœ¬-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬-æ‰‹åŠ¨
      - â™»ï¸ æ—¥æœ¬-è‡ªåŠ¨
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan)).*$"
  - name: â™»ï¸ æ—¥æœ¬-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan)).*$"

  # æ–°åŠ å¡ç»„
  - name: ğŸ”¯ æ–°åŠ å¡-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-æ‰‹åŠ¨
      - â™»ï¸ æ–°åŠ å¡-è‡ªåŠ¨
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)).*$"
  - name: â™»ï¸ æ–°åŠ å¡-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)).*$"

  # éŸ©å›½ç»„
  - name: ğŸ”¯ éŸ©å›½-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡°ğŸ‡· éŸ©å›½-æ‰‹åŠ¨
      - â™»ï¸ éŸ©å›½-è‡ªåŠ¨
  - name: ğŸ‡°ğŸ‡· éŸ©å›½-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)).*$"
  - name: â™»ï¸ éŸ©å›½-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)).*$"

  # ç¾å›½ç»„
  - name: ğŸ”¯ ç¾å›½-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡ºğŸ‡¸ ç¾å›½-æ‰‹åŠ¨
      - â™»ï¸ ç¾å›½-è‡ªåŠ¨
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).*$"
  - name: â™»ï¸ ç¾å›½-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).*$"

  # è‹±å›½ç»„
  - name: ğŸ”¯ è‹±å›½-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡¬ğŸ‡§ è‹±å›½-æ‰‹åŠ¨
      - â™»ï¸ è‹±å›½-è‡ªåŠ¨
  - name: ğŸ‡¬ğŸ‡§ è‹±å›½-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(è‹±å›½|è‹±|ä¼¦æ•¦|UK|United Kingdom|ğŸ‡¬ğŸ‡§|London)).*$"
  - name: â™»ï¸ è‹±å›½-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(è‹±å›½|è‹±|ä¼¦æ•¦|UK|United Kingdom|ğŸ‡¬ğŸ‡§|London)).*$"

  # å…¶ä»–ç»„
  - name: ğŸ”¯ å…¶ä»–-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸŒ å…¶ä»–-æ‰‹åŠ¨
      - â™»ï¸ å…¶ä»–-è‡ªåŠ¨
  - name: ğŸŒ å…¶ä»–-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "^((?!(ç›´è¿|æ‹’ç»|å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong|å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|TaiWan|Taiwan|å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan|å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea|å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States|è‹±å›½|UK|United Kingdom|ä¼¦æ•¦|è‹±|London|ğŸ‡¬ğŸ‡§)).)*$"
  - name: â™»ï¸ å…¶ä»–-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "^((?!(ç›´è¿|æ‹’ç»|å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong|å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|TaiWan|Taiwan|å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan|å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea|å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States|è‹±å›½|UK|United Kingdom|ä¼¦æ•¦|è‹±|London|ğŸ‡¬ğŸ‡§)).)*$"

# è§„åˆ™åŒ¹é…
rules:
  - RULE-SET,private_ip,ç›´è¿,no-resolve
  - RULE-SET,private_domain,ç›´è¿
#  - DOMAIN-SUFFIX,qichiyu.com,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,proxylite,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,ai,ğŸ¤– ChatGPT
  - RULE-SET,github_domain,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,google_domain,ğŸ€ Google
  - RULE-SET,onedrive_domain,ğŸ¬ OneDrive
  - RULE-SET,microsoft_domain,ğŸªŸ Microsoft
  - RULE-SET,apple_domain,ç›´è¿
  - RULE-SET,tiktok_domain,ğŸµ TikTok
  - RULE-SET,telegram_domain,ğŸ“² Telegram
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal
  - RULE-SET,apple_ip,ç›´è¿
  - RULE-SET,google_ip,ğŸ€ Google
  - RULE-SET,netflix_ip,ğŸ¥ NETFLIX
  - RULE-SET,telegram_ip,ğŸ“² Telegram
  - RULE-SET,steamcn,ğŸ® GAME-CN
  - RULE-SET,epic,ğŸ® GAME-CN
  - RULE-SET,gamecn,ğŸ® GAME-CN
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,cn_domain,ç›´è¿
  - RULE-SET,cn_ip,ç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

# è§„åˆ™é›†
## typeï¼šå¯é€‰http/file/inline  behaviorï¼šå¯é€‰domain/ipcidr/classical formatï¼šå¯é€‰yaml/text/mrs
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  fakeipfilter_domain: {<<: *domain, url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs"}
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list"}
  steamcn: { <<: *class, url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.list"}
  epic: { <<: *class, url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Epic/Epic.list"}
  gamecn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games@cn.mrs"}
  ai: {  <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  
  private_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  apple_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}
