proxy-providers:
  Sakuraca:
    url: ""
    type: http
    interval: 345600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    override:
      additional-prefix: "Sakuraca-"
    exclude-filter: "x|å€|æ¶ˆè€—|å®˜ç½‘|åˆ°æœŸ|é‡ç½®|å‰©ä½™|æµ·å¤–|å¯¼èˆª"
    proxy: ç›´è¿
  SaySS:
    url: ""
    type: http
    interval: 345600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    override:
      additional-prefix: "SaySS-"
    exclude-filter: "x|å€|æ¶ˆè€—|å®˜ç½‘|åˆ°æœŸ|é‡ç½®|å‰©ä½™|æµ·å¤–|å¯¼èˆª"
    proxy: ç›´è¿
  CockCloud:
    url: ""
    type: http
    interval: 345600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    override:
      additional-prefix: "CockCloud-"
    exclude-filter: "x|å€|æ¶ˆè€—|å®˜ç½‘|åˆ°æœŸ|é‡ç½®|å‰©ä½™|æµ·å¤–|å¯¼èˆª"
    proxy: ç›´è¿
   

proxies:
  - {name: ç›´è¿, type: direct}
  - {name: æ‹’ç», type: reject}


mixed-port: 7890
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
tcp-concurrent: true
log-level: warning
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

al: &al 'https://223.5.5.5/dns-query#ç›´è¿'
tx: &tx 'https://doh.pub/dns-query#ç›´è¿&h3=false'
gg: &gg 'https://8.8.8.8/dns-query#RULES&ecs=8.8.8.8/32&ecs-override=true'
cf: &cf 'https://1.1.1.1/dns-query#RULES&ecs=1.1.1.1/32&ecs-override=true'
dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:1053
  ipv6: true
  respect-rules: false
  enhanced-mode: redir-host
  default-nameserver: ['https://223.5.5.5/dns-query']
  proxy-server-nameserver: [*al,*tx]
  direct-nameserver: [system,*al,*tx]
  direct-nameserver-follow-policy: true
  nameserver-policy:
    "rule-set:proxylite": [*gg,*cf]
    "rule-set:alibaba_domain,private_domain,steamcn,epic,gamecn,oppo_domain,cn_domain": [system,*al,*tx]
  nameserver: [*gg,*cf]

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "rule-set:cn_domain,private_domain,steamcn,epic,gamecn,fakeipfilter_domain"
  force-domain:
    - "rule-set:netflix_domain,youtube_domain"
  skip-src-address:
    - "rule-set:cn_ip,private_ip"
   

default: &default
  type: select
  proxies:
    - ğŸš€ é»˜è®¤ä»£ç†
    - â™»ï¸ æ‰€æœ‰-è‡ªåŠ¨
    - ğŸ”¯ é¦™æ¸¯-æ•…è½¬
    - ğŸ”¯ å°æ¹¾-æ•…è½¬
    - ğŸ”¯ æ—¥æœ¬-æ•…è½¬
    - ğŸ”¯ æ–°åŠ å¡-æ•…è½¬
    - ğŸ”¯ éŸ©å›½-æ•…è½¬
    - ğŸ”¯ ç¾å›½-æ•…è½¬
    - ğŸ”¯ è‹±å›½-æ•…è½¬
    - ğŸ”¯ å…¶ä»–-æ•…è½¬
    - ç›´è¿
    - æ‹’ç»
default_no_allmanual: &default_no_allmanual
  type: select
  proxies:
    - â™»ï¸ æ‰€æœ‰-è‡ªåŠ¨
    - ğŸ”¯ é¦™æ¸¯-æ•…è½¬
    - ğŸ”¯ å°æ¹¾-æ•…è½¬
    - ğŸ”¯ æ—¥æœ¬-æ•…è½¬
    - ğŸ”¯ æ–°åŠ å¡-æ•…è½¬
    - ğŸ”¯ éŸ©å›½-æ•…è½¬
    - ğŸ”¯ ç¾å›½-æ•…è½¬
    - ğŸ”¯ è‹±å›½-æ•…è½¬
    - ğŸ”¯ å…¶ä»–-æ•…è½¬
    - ç›´è¿
    - æ‹’ç»


proxy-groups:

  - {name: ğŸš€ é»˜è®¤ä»£ç†, <<: *default_no_allmanual, include-all: true,filter: "^((?!(ç›´è¿|æ‹’ç»|DROP)).)*$"}
  - {name: ğŸ“¹ YouTube, <<: *default}
  - {name: ğŸ€ Google, <<: *default}
  - {name: ğŸ¤– ChatGPT, <<: *default}
  - {name: ğŸ‘¨ğŸ¿â€ğŸ’» GitHub, <<: *default}
  - {name: ğŸªŸ bing, <<: *default}
  - {name: ğŸ¬ OneDrive, <<: *default}
  - {name: ğŸªŸ Microsoft, <<: *default}
  - {name: ğŸµ TikTok, <<: *default}
  - {name: ğŸ“² Telegram, <<: *default}
  - {name: ğŸ¥ NETFLIX, <<: *default}
  - {name: ğŸ’¶ PayPal, <<: *default}
  - {name: ğŸ® GAME-CN, <<: *default}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, <<: *default}
  

  - name: â™»ï¸ æ‰€æœ‰-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$"

  - name: ğŸ”¯ é¦™æ¸¯-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-æ‰‹åŠ¨
      - â™»ï¸ é¦™æ¸¯-è‡ªåŠ¨
  
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong)).*$"
    
  - name: â™»ï¸ é¦™æ¸¯-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong)).*$"
 
  - name: ğŸ”¯ å°æ¹¾-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾-æ‰‹åŠ¨
      - â™»ï¸ å°æ¹¾-è‡ªåŠ¨
  - name: ğŸ‡¹ğŸ‡¼ å°æ¹¾-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|TaiWan|Taiwan)).*$"
  - name: â™»ï¸ å°æ¹¾-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|TaiWan|Taiwan)).*$"

  - name: ğŸ”¯ æ—¥æœ¬-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬-æ‰‹åŠ¨
      - â™»ï¸ æ—¥æœ¬-è‡ªåŠ¨
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan)).*$"
  - name: â™»ï¸ æ—¥æœ¬-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan)).*$"
  - name: ğŸ”¯ æ–°åŠ å¡-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-æ‰‹åŠ¨
      - â™»ï¸ æ–°åŠ å¡-è‡ªåŠ¨
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)).*$"
  - name: â™»ï¸ æ–°åŠ å¡-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)).*$"

  - name: ğŸ”¯ éŸ©å›½-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡°ğŸ‡· éŸ©å›½-æ‰‹åŠ¨
      - â™»ï¸ éŸ©å›½-è‡ªåŠ¨
  - name: ğŸ‡°ğŸ‡· éŸ©å›½-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)).*$"
  - name: â™»ï¸ éŸ©å›½-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)).*$"

  - name: ğŸ”¯ ç¾å›½-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡ºğŸ‡¸ ç¾å›½-æ‰‹åŠ¨
      - â™»ï¸ ç¾å›½-è‡ªåŠ¨
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).*$"
  - name: â™»ï¸ ç¾å›½-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).*$"

  - name: ğŸ”¯ è‹±å›½-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸ‡¬ğŸ‡§ è‹±å›½-æ‰‹åŠ¨
      - â™»ï¸ è‹±å›½-è‡ªåŠ¨
  - name: ğŸ‡¬ğŸ‡§ è‹±å›½-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(è‹±å›½|è‹±|ä¼¦æ•¦|UK|United Kingdom|ğŸ‡¬ğŸ‡§|London)).*$"
  - name: â™»ï¸ è‹±å›½-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(è‹±å›½|è‹±|ä¼¦æ•¦|UK|United Kingdom|ğŸ‡¬ğŸ‡§|London)).*$"


  - name: ğŸ”¯ å…¶ä»–-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ğŸŒ å…¶ä»–-æ‰‹åŠ¨
      - â™»ï¸ å…¶ä»–-è‡ªåŠ¨
  - name: ğŸŒ å…¶ä»–-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "^((?!(ç›´è¿|æ‹’ç»|DROP|å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong|å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|TaiWan|Taiwan|å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan|å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea|å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States|è‹±å›½|UK|United Kingdom|ä¼¦æ•¦|è‹±|London|ğŸ‡¬ğŸ‡§)).)*$"
  - name: â™»ï¸ å…¶ä»–-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "^((?!(ç›´è¿|æ‹’ç»|DROP|å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong|å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|TaiWan|Taiwan|å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan|å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea|å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States|è‹±å›½|UK|United Kingdom|ä¼¦æ•¦|è‹±|London|ğŸ‡¬ğŸ‡§)).)*$"

rules:
  - RULE-SET,proxylite,ğŸš€ é»˜è®¤ä»£ç†
  - OR,((RULE-SET,private_ip,no-resolve),(RULE-SET,private_domain),(RULE-SET,tailscale),(RULE-SET,ntp_cn),(RULE-SET,aliasn_ip,no-resolve),(RULE-SET,alibaba_domain),(RULE-SET,oppo_domain)),ç›´è¿
  - RULE-SET,ai,ğŸ¤– ChatGPT
  - RULE-SET,github_domain,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - OR,((RULE-SET,google_domain),(RULE-SET,google_ip)),ğŸ€ Google
  - RULE-SET,bing_domain,ğŸªŸ bing
  - RULE-SET,onedrive_domain,ğŸ¬ OneDrive
  - RULE-SET,microsoft_domain,ğŸªŸ Microsoft
  - RULE-SET,tiktok_domain,ğŸµ TikTok
  - OR,((RULE-SET,telegram_domain),(RULE-SET,telegram_ip,no-resolve)),ğŸ“² Telegram
  - OR,((RULE-SET,netflix_domain),(RULE-SET,netflix_ip,no-resolve)),ğŸ¥ NETFLIX
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal
  - OR,((RULE-SET,apple_ip,no-resolve),(RULE-SET,apple_domain)),ç›´è¿
  - OR,((RULE-SET,steamcn),(RULE-SET,epic),(RULE-SET,gamecn)),ğŸ® GAME-CN
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†
  - OR,((RULE-SET,cn_domain),(RULE-SET,cn_ip)),ç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

rule-anchor:
  ip: &ip {type: http, interval: 345600, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 345600, behavior: domain, format: mrs}
  class: &class {type: http, interval: 345600, behavior: classical, format: text}
rule-providers: 
  tailscale: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tailscale.mrs", path: ./rules/tailscale.mrs}
  ntp_cn: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ntp@cn.mrs", path: ./rules/category-ntp@cn.mrs}
  fakeipfilter_domain: {<<: *domain, url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs", path: ./rules/fakeip-filter.mrs}
  private_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs", path: ./rules/private.mrs}
  proxylite: {<<: *class, url: "https://raw.githubusercontent.com/canary625/rule/refs/heads/main/proxy.list", path: ./rules/proxy.list}
  steamcn: {<<: *class, url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.list", path: ./rules/SteamCN.list}
  epic: {<<: *class, url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Epic/Epic.list", path: ./rules/Epic.list}
  gamecn: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games@cn.mrs", path: ./rules/category-games@cn.mrs}
  ai: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs", path: ./rules/category-ai-!cn.mrs}
  youtube_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs", path: ./rules/youtube.mrs}
  google_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs", path: ./rules/google.mrs}
  github_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs", path: ./rules/github.mrs}
  telegram_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs", path: ./rules/telegram.mrs}
  netflix_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs", path: ./rules/netflix.mrs}
  paypal_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs", path: ./rules/paypal.mrs}
  onedrive_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs", path: ./rules/onedrive.mrs}
  microsoft_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs", path: ./rules/microsoft.mrs}
  apple_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs", path: ./rules/apple.mrs}
  speedtest_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs", path: ./rules/ookla-speedtest.mrs}
  tiktok_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs", path: ./rules/tiktok.mrs}
  geolocation-!cn: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs", path: ./rules/geolocation-!cn.mrs}
  cn_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs", path: ./rules/cn.mrs}
  private_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs", path: ./rules/private.mrs}
  cn_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs", path: ./rules/cn.mrs}
  google_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs", path: ./rules/google.mrs}
  telegram_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs", path: ./rules/telegram.mrs}
  netflix_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs", path: ./rules/netflix.mrs}
  apple_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs", path: ./rules/apple.mrs}
  alibaba_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/alibaba.mrs", path: ./rules/alibaba.mrs}
  aliasn_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/asn/AS45102.mrs", path: ./rules/AS45102.mrs}
  oppo_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/oppo.mrs", path: ./rules/oppo.mrs}
  bing_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bing.mrs", path: ./rules/bing.mrs}
